#include <algorithm>
#include <array>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <cstdlib>
#include <iostream>
#include <limits>
#include <memory>
#include <span>
#include <string>
#include <string_view>
#include <vector>

#include "src/models/deepseek_v4_flash/engine.hpp"

namespace {

void Expect(bool condition, const char* message) {
  if (!condition) {
    std::cerr << "FAIL: " << message << '\n';
    std::abort();
  }
}

constexpr std::string_view kTrajectoryPrompt =
    "Continue this technical explanation with concrete examples and "
    "tradeoffs: Virtual memory lets an operating system";

// Generated by antirez/ds4 revision 84cc882352757baf628a1776badf7cc54d584e28.
constexpr std::array<int, 128> kPinnedDs4Trajectory{
    1347,  17491, 305,  11586, 8412,  412,  260,  1840,  6464,  14261, 16,
    983,   18954, 6781, 294,   1192,  1949, 6464, 436,   6623,  343,   458,
    1205,  436,   344,  1505,  362,   11,   5566, 6460,  305,   17491, 11096,
    16,    983,   4491, 6464,  19627, 3510, 304,  6783,  16,    983,   4491,
    270,   1487,  850,  10920, 16,    1890, 436,  28162, 260,   1699,  1347,
    850,   6464,  1099, 344,   22920, 3510, 16,   455,   1840,  41036, 477,
    28,    7294,  469,  850,   4190,  6783, 29,   15842, 4256,  1014,  29,
    305,   3283,  362,  1487,  31489, 3504, 304,  5167,  18585, 4346,  91604,
    16,    983,   588,  990,   1635,  260,  1487, 39376, 16,    983,   6026,
    25454, 1014,  304,  10181, 6464,  16,   983,  6026,  1014,  304,   30376,
    16,    983,   9347, 270,   15599, 294,  270,  20616, 14,    2918,  436,
    2231,  366,   9026, 295,   6464,  9694, 436,
};

void CheckPinnedTrajectory(
    const std::shared_ptr<gufo::models::deepseek_v4_flash::Model>& model) {
  std::string error;
  const auto prompt = model->Tokenize(kTrajectoryPrompt);
  Expect(!prompt.empty(), "trajectory prompt tokenization");

  auto session = model->CreateSession(512, &error);
  Expect(session != nullptr, error.c_str());
  Expect(session->Sync(prompt, &error), error.c_str());

  int top1_matches = 0;
  std::uint64_t rank_sum = 0;
  int worst_rank = 0;
  for (const int expected_token : kPinnedDs4Trajectory) {
    const auto logits = session->CopyLogits(&error);
    Expect(!logits.empty(), error.c_str());
    Expect(expected_token >= 0 &&
               static_cast<std::size_t>(expected_token) < logits.size(),
           "trajectory token range");

    const int selected_token = session->SelectNext(0.0F, nullptr);
    const float expected_logit =
        logits[static_cast<std::size_t>(expected_token)];
    const int rank =
        1 + static_cast<int>(std::count_if(logits.begin(), logits.end(),
                                           [expected_logit](float value) {
                                             return value > expected_logit;
                                           }));
    top1_matches += selected_token == expected_token ? 1 : 0;
    rank_sum += static_cast<std::uint64_t>(rank);
    worst_rank = std::max(worst_rank, rank);

    Expect(session->Evaluate(expected_token, &error), error.c_str());
  }

  std::cout << "Pinned DS4 trajectory: top1=" << top1_matches
            << "/128 rank_sum=" << rank_sum << " worst_rank=" << worst_rank
            << '\n';
  Expect(top1_matches >= 116, "128-token top-1 agreement");
  Expect(rank_sum <= 142, "128-token aggregate rank");
  Expect(worst_rank <= 3, "128-token worst rank");
}

void CheckBatchedPrefill(
    const std::shared_ptr<gufo::models::deepseek_v4_flash::Model>& model) {
  constexpr int kTrajectoryRepetitions = 2;

  std::string error;
  const auto prompt = model->Tokenize(kTrajectoryPrompt);
  Expect(!prompt.empty(), "prefill prompt tokenization");
  auto tokens = prompt;
  for (int repetition = 0; repetition < kTrajectoryRepetitions; ++repetition) {
    tokens.insert(tokens.end(), kPinnedDs4Trajectory.begin(),
                  kPinnedDs4Trajectory.end());
  }

  auto batched = model->CreateSession(4096, &error);
  Expect(batched != nullptr, error.c_str());
  Expect(batched->Sync(tokens, &error), error.c_str());
  const auto batched_logits = batched->CopyLogits(&error);
  Expect(!batched_logits.empty(), error.c_str());

  auto sequential = model->CreateSession(4096, &error);
  Expect(sequential != nullptr, error.c_str());
  Expect(sequential->Sync(prompt, &error), error.c_str());
  for (int repetition = 0; repetition < kTrajectoryRepetitions; ++repetition) {
    for (const int token : kPinnedDs4Trajectory) {
      Expect(sequential->Evaluate(token, &error), error.c_str());
    }
  }
  const auto sequential_logits = sequential->CopyLogits(&error);
  Expect(sequential_logits.size() == batched_logits.size(),
         "prefill logit shape");

  double squared_error = 0.0;
  double dot = 0.0;
  double batched_norm = 0.0;
  double sequential_norm = 0.0;
  float max_error = 0.0F;
  bool finite = true;
  for (std::size_t index = 0; index < batched_logits.size(); ++index) {
    const float batched_value = batched_logits[index];
    const float sequential_value = sequential_logits[index];
    finite = finite && std::isfinite(batched_value) &&
             std::isfinite(sequential_value);
    const double difference =
        static_cast<double>(batched_value) - sequential_value;
    squared_error += difference * difference;
    dot += static_cast<double>(batched_value) * sequential_value;
    batched_norm += static_cast<double>(batched_value) * batched_value;
    sequential_norm += static_cast<double>(sequential_value) * sequential_value;
    max_error = std::max(max_error, std::abs(batched_value - sequential_value));
  }

  const double rmse =
      std::sqrt(squared_error / static_cast<double>(batched_logits.size()));
  const double denominator = std::sqrt(batched_norm * sequential_norm);
  const double cosine = denominator > std::numeric_limits<double>::min()
                            ? dot / denominator
                            : 0.0;
  const auto batched_top =
      std::max_element(batched_logits.begin(), batched_logits.end());
  const auto sequential_top =
      std::max_element(sequential_logits.begin(), sequential_logits.end());
  const auto batched_top_index = static_cast<std::size_t>(
      std::distance(batched_logits.begin(), batched_top));
  const auto sequential_top_index = static_cast<std::size_t>(
      std::distance(sequential_logits.begin(), sequential_top));
  const float sequential_choice_logit = batched_logits[sequential_top_index];
  const int sequential_choice_rank =
      1 + static_cast<int>(
              std::count_if(batched_logits.begin(), batched_logits.end(),
                            [sequential_choice_logit](float value) {
                              return value > sequential_choice_logit;
                            }));

  std::cout << "Batched prefill (" << tokens.size()
            << " tokens) vs sequential: rmse=" << rmse << " cosine=" << cosine
            << " max_error=" << max_error
            << " top1_match=" << (batched_top_index == sequential_top_index)
            << " sequential_choice_rank=" << sequential_choice_rank << '\n';
  Expect(finite, "prefill finite logits");
  Expect(rmse <= 1.12, "prefill RMSE envelope");
  Expect(cosine >= 0.979, "prefill cosine envelope");
  Expect(max_error <= 5.0F, "prefill maximum error envelope");
  Expect(sequential_choice_rank <= 3, "prefill sequential choice rank");
}

void CheckConversationalPrefill(
    const std::shared_ptr<gufo::models::deepseek_v4_flash::Model>& model) {
  constexpr std::array<std::size_t, 3> kWidths{32, 64, 96};

  std::string error;
  const auto prompt = model->Tokenize(kTrajectoryPrompt);
  Expect(!prompt.empty(), "conversational prefill prompt tokenization");
  for (const std::size_t width : kWidths) {
    auto tokens = prompt;
    for (std::size_t index = 0; tokens.size() < width; ++index) {
      tokens.push_back(
          kPinnedDs4Trajectory[index % kPinnedDs4Trajectory.size()]);
    }

    auto batched = model->CreateSession(512, &error);
    Expect(batched != nullptr, error.c_str());
    Expect(batched->Sync(tokens, &error), error.c_str());
    const auto batched_logits = batched->CopyLogits(&error);
    Expect(!batched_logits.empty(), error.c_str());

    auto sequential = model->CreateSession(512, &error);
    Expect(sequential != nullptr, error.c_str());
    const std::vector<int> first_token{tokens.front()};
    Expect(sequential->Sync(first_token, &error), error.c_str());
    for (std::size_t index = 1; index < tokens.size(); ++index) {
      Expect(sequential->Evaluate(tokens[index], &error), error.c_str());
    }
    const auto sequential_logits = sequential->CopyLogits(&error);
    Expect(sequential_logits.size() == batched_logits.size(),
           "conversational prefill logit shape");

    double squared_error = 0.0;
    double dot = 0.0;
    double batched_norm = 0.0;
    double sequential_norm = 0.0;
    float max_error = 0.0F;
    bool finite = true;
    for (std::size_t index = 0; index < batched_logits.size(); ++index) {
      const float batched_value = batched_logits[index];
      const float sequential_value = sequential_logits[index];
      finite = finite && std::isfinite(batched_value) &&
               std::isfinite(sequential_value);
      const double difference =
          static_cast<double>(batched_value) - sequential_value;
      squared_error += difference * difference;
      dot += static_cast<double>(batched_value) * sequential_value;
      batched_norm += static_cast<double>(batched_value) * batched_value;
      sequential_norm +=
          static_cast<double>(sequential_value) * sequential_value;
      max_error =
          std::max(max_error, std::abs(batched_value - sequential_value));
    }
    const double rmse =
        std::sqrt(squared_error / static_cast<double>(batched_logits.size()));
    const double denominator = std::sqrt(batched_norm * sequential_norm);
    const double cosine = denominator > std::numeric_limits<double>::min()
                              ? dot / denominator
                              : 0.0;
    const auto batched_top =
        std::max_element(batched_logits.begin(), batched_logits.end());
    const auto sequential_top =
        std::max_element(sequential_logits.begin(), sequential_logits.end());
    const auto batched_top_index = static_cast<std::size_t>(
        std::distance(batched_logits.begin(), batched_top));
    const auto sequential_top_index = static_cast<std::size_t>(
        std::distance(sequential_logits.begin(), sequential_top));
    const float sequential_choice_logit = batched_logits[sequential_top_index];
    const int sequential_choice_rank =
        1 + static_cast<int>(
                std::count_if(batched_logits.begin(), batched_logits.end(),
                              [sequential_choice_logit](float value) {
                                return value > sequential_choice_logit;
                              }));

    std::cout << "Conversational prefill (" << width
              << " tokens) vs sequential: rmse=" << rmse << " cosine=" << cosine
              << " max_error=" << max_error
              << " top1_match=" << (batched_top_index == sequential_top_index)
              << " sequential_choice_rank=" << sequential_choice_rank << '\n';
    Expect(finite, "conversational prefill finite logits");
    Expect(rmse <= 1.12, "conversational prefill RMSE envelope");
    Expect(cosine >= 0.979, "conversational prefill cosine envelope");
    Expect(max_error <= 5.0F, "conversational prefill maximum error envelope");
    Expect(sequential_choice_rank <= 3,
           "conversational prefill sequential choice rank");
  }
}

void CheckSessionBatch(
    const std::shared_ptr<gufo::models::deepseek_v4_flash::Model>& model) {
  using gufo::models::deepseek_v4_flash::SessionBatchItem;

  constexpr std::array<std::string_view, 8> kPrompts{
      "Explain virtual memory in one paragraph.",
      "Write a short C++ function that adds two integers.",
      "What causes ocean tides? Answer concisely.",
      "List three practical ways to reduce database query latency.",
      "Describe how a hash table handles collisions.",
      "Give one advantage of immutable data structures.",
      "Why do compilers inline small functions?",
      "Name two ways to reduce network request latency.",
  };
  constexpr std::array<std::size_t, 8> kPromptTokens{
      32, 48, 64, 96, 128, 160, 192, 256,
  };

  std::string error;
  std::array<std::vector<int>, 8> session_prompts;
  std::array<std::unique_ptr<gufo::models::deepseek_v4_flash::Session>, 8>
      batched;
  std::array<std::unique_ptr<gufo::models::deepseek_v4_flash::Session>, 8>
      sequential;
  for (std::size_t index = 0; index < kPrompts.size(); ++index) {
    const auto prompt =
        model->EncodeChat("You are a concise assistant.", kPrompts[index]);
    Expect(!prompt.empty(), "session batch prompt tokenization");
    auto extended_prompt = prompt;
    for (std::size_t token = 0; extended_prompt.size() < kPromptTokens[index];
         ++token) {
      extended_prompt.push_back(
          kPinnedDs4Trajectory[token % kPinnedDs4Trajectory.size()]);
    }
    session_prompts[index] = std::move(extended_prompt);
  }
  const auto reset_sessions = [&] {
    for (std::size_t index = 0; index < kPrompts.size(); ++index) {
      batched[index] = model->CreateSession(512, &error);
      sequential[index] = model->CreateSession(512, &error);
      Expect(batched[index] != nullptr, error.c_str());
      Expect(sequential[index] != nullptr, error.c_str());
      Expect(batched[index]->Sync(session_prompts[index], &error),
             error.c_str());
      Expect(sequential[index]->Sync(session_prompts[index], &error),
             error.c_str());
      Expect(batched[index]->SelectNext(0.0F, nullptr) ==
                 sequential[index]->SelectNext(0.0F, nullptr),
             "session batch initial greedy token");
    }
  };
  reset_sessions();

  const int position0 = batched[0]->Position();
  const int position1 = batched[1]->Position();
  const int token0 = batched[0]->SelectNext(0.0F, nullptr);
  const int token1 = batched[1]->SelectNext(0.0F, nullptr);
  const auto expect_preflight_rejection =
      [&](std::span<const SessionBatchItem> items, const char* message) {
        Expect(!model->EvaluateBatch(items, &error), message);
        Expect(batched[0]->Position() == position0 &&
                   batched[1]->Position() == position1,
               "session batch preflight preserves positions");
      };

  const std::array<SessionBatchItem, 2> duplicate_items{{
      {.session = batched[0].get(), .token = token0},
      {.session = batched[0].get(), .token = token0},
  }};
  expect_preflight_rejection(duplicate_items,
                             "session batch rejects duplicate sessions");

  const std::array<SessionBatchItem, 2> invalid_token_items{{
      {.session = batched[0].get(), .token = token0},
      {.session = batched[1].get(), .token = model->VocabSize()},
  }};
  expect_preflight_rejection(invalid_token_items,
                             "session batch rejects invalid tokens");

  batched[1]->SetCancellationCheck([] { return true; });
  const std::array<SessionBatchItem, 2> cancelled_items{{
      {.session = batched[0].get(), .token = token0},
      {.session = batched[1].get(), .token = token1},
  }};
  expect_preflight_rejection(cancelled_items,
                             "session batch rejects cancelled sessions");
  batched[1]->SetCancellationCheck({});

  int comparisons = 0;
  int top1_matches = 0;
  double worst_rmse = 0.0;
  double worst_cosine = 1.0;
  float worst_max_error = 0.0F;
  int worst_sequential_choice_rank = 0;
  const auto compare = [&](std::size_t index) {
    const int batched_token = batched[index]->SelectNext(0.0F, nullptr);
    const int sequential_token = sequential[index]->SelectNext(0.0F, nullptr);
    const auto batched_logits = batched[index]->CopyLogits(&error);
    const auto sequential_logits = sequential[index]->CopyLogits(&error);
    Expect(batched_logits.size() == sequential_logits.size(),
           "session batch logit shape");
    double squared_error = 0.0;
    double dot = 0.0;
    double batched_norm = 0.0;
    double sequential_norm = 0.0;
    float max_error = 0.0F;
    bool finite = true;
    for (std::size_t token_index = 0; token_index < batched_logits.size();
         ++token_index) {
      const float batched_value = batched_logits[token_index];
      const float sequential_value = sequential_logits[token_index];
      finite = finite && std::isfinite(batched_value) &&
               std::isfinite(sequential_value);
      const double difference =
          static_cast<double>(batched_value) - sequential_value;
      squared_error += difference * difference;
      dot += static_cast<double>(batched_value) * sequential_value;
      batched_norm += static_cast<double>(batched_value) * batched_value;
      sequential_norm +=
          static_cast<double>(sequential_value) * sequential_value;
      max_error =
          std::max(max_error, std::abs(batched_value - sequential_value));
    }
    const double rmse =
        std::sqrt(squared_error / static_cast<double>(batched_logits.size()));
    const double denominator = std::sqrt(batched_norm * sequential_norm);
    const double cosine = denominator > std::numeric_limits<double>::min()
                              ? dot / denominator
                              : 0.0;
    const float sequential_choice_logit =
        batched_logits[static_cast<std::size_t>(sequential_token)];
    const int sequential_choice_rank =
        1 + static_cast<int>(
                std::count_if(batched_logits.begin(), batched_logits.end(),
                              [sequential_choice_logit](float value) {
                                return value > sequential_choice_logit;
                              }));

    ++comparisons;
    top1_matches += batched_token == sequential_token ? 1 : 0;
    worst_rmse = std::max(worst_rmse, rmse);
    worst_cosine = std::min(worst_cosine, cosine);
    worst_max_error = std::max(worst_max_error, max_error);
    worst_sequential_choice_rank =
        std::max(worst_sequential_choice_rank, sequential_choice_rank);
    if (batched_token != sequential_token || rmse > 0.85 || cosine < 0.99 ||
        max_error > 4.5F || sequential_choice_rank > 3) {
      std::cout << "Session batch quality detail: member=" << index
                << " position=" << batched[index]->Position()
                << " batched=" << batched_token
                << " sequential=" << sequential_token << " rmse=" << rmse
                << " cosine=" << cosine << " max_error=" << max_error
                << " sequential_choice_rank=" << sequential_choice_rank << '\n';
    }
    Expect(finite, "session batch finite logits");
    Expect(rmse <= 0.85, "session batch RMSE envelope");
    Expect(cosine >= 0.99, "session batch cosine envelope");
    Expect(max_error <= 4.5F, "session batch maximum error envelope");
    Expect(sequential_choice_rank <= 3, "session batch sequential choice rank");
  };

  const auto advance = [&](std::span<const std::size_t> members) {
    std::vector<SessionBatchItem> items;
    items.reserve(members.size());
    for (const std::size_t index : members) {
      const int token = sequential[index]->SelectNext(0.0F, nullptr);
      Expect(sequential[index]->Evaluate(token, &error), error.c_str());
      items.push_back({.session = batched[index].get(), .token = token});
    }
    Expect(model->EvaluateBatch(items, &error), error.c_str());
    for (const std::size_t index : members) {
      Expect(batched[index]->Position() == sequential[index]->Position(),
             "session batch position");
      compare(index);
    }
  };

  constexpr std::array<std::size_t, 6> kAllSix{0, 1, 2, 3, 4, 5};
  advance(kAllSix);
  reset_sessions();

  constexpr std::array<std::size_t, 4> kAll{0, 1, 2, 3};
  for (int step = 0; step < 3; ++step) {
    advance(kAll);
  }

  constexpr std::array<std::size_t, 2> kChangedMembership{0, 2};
  advance(kChangedMembership);

  constexpr std::array<std::size_t, 8> kAllEight{0, 1, 2, 3, 4, 5, 6, 7};
  advance(kAllEight);

  const int token = sequential[0]->SelectNext(0.0F, nullptr);
  Expect(sequential[0]->Evaluate(token, &error), error.c_str());
  Expect(batched[0]->Evaluate(token, &error), error.c_str());
  compare(0);

  std::cout << "DeepSeek V4 session batch quality: top1=" << top1_matches << '/'
            << comparisons << " worst_rmse=" << worst_rmse
            << " worst_cosine=" << worst_cosine
            << " worst_max_error=" << worst_max_error
            << " worst_sequential_choice_rank=" << worst_sequential_choice_rank
            << '\n';
}

void CheckDsparkPromptSeed(
    const std::shared_ptr<gufo::models::deepseek_v4_flash::Model>& model) {
  std::string error;
  const auto prompt = model->EncodeChat(
      "You are a helpful assistant",
      "The quick brown fox jumps over the lazy dog. Explain why.");
  Expect(!prompt.empty(), "DSpark seed prompt tokenization");

  auto session = model->CreateSession(512, &error);
  Expect(session != nullptr, error.c_str());
  Expect(session->Sync(prompt, &error), error.c_str());
  auto stats = session->DsparkStatistics();
  Expect(stats.context_tokens >= prompt.size(),
         "DSpark prefill seeds the complete prompt");

  std::vector<int> emitted;
  Expect(session->DsparkStep(&emitted, &error), error.c_str());
  Expect(!emitted.empty(), "DSpark first step emitted tokens");
  stats = session->DsparkStatistics();
  Expect(stats.context_tokens >= prompt.size(),
         "first DSpark cycle retains complete prompt coverage");
  Expect(stats.steps == 1, "DSpark drafts on the first generation cycle");
  Expect(stats.anchors == 1, "DSpark records one target-known anchor");
  Expect(stats.support_drafted == 5, "DSpark records five support rows");
  Expect(stats.verifier_rows == 6, "DSpark verifies anchor plus support rows");

  auto short_extension = prompt;
  short_extension.push_back(emitted.front());
  short_extension.push_back(session->SelectNext(0.0F, nullptr));
  session.reset();

  auto extended = model->CreateSession(512, &error);
  Expect(extended != nullptr, error.c_str());
  Expect(extended->Sync(prompt, &error), error.c_str());
  Expect(extended->Sync(short_extension, &error), error.c_str());
  Expect(extended->DsparkStatistics().context_tokens == short_extension.size(),
         "short checkpoint extension seeds and extends DSpark context");
  emitted.clear();
  Expect(extended->DsparkStep(&emitted, &error), error.c_str());
  Expect(extended->DsparkStatistics().context_tokens >= short_extension.size(),
         "first draft after extension seeds the captured suffix");
  extended.reset();

  auto snapshot_source = model->CreateSession(512, &error);
  Expect(snapshot_source != nullptr, error.c_str());
  Expect(snapshot_source->Sync(prompt, &error), error.c_str());
  auto snapshot = snapshot_source->SaveSnapshot(&error);
  Expect(snapshot != nullptr, error.c_str());
  snapshot_source.reset();

  auto restored = model->CreateSession(512, &error);
  Expect(restored != nullptr, error.c_str());
  Expect(restored->RestoreSnapshot(*snapshot, &error), error.c_str());
  Expect(restored->DsparkStatistics().context_tokens == 0,
         "snapshot restore does not claim absent DSpark context");
  emitted.clear();
  Expect(restored->DsparkStep(&emitted, &error), error.c_str());
  Expect(emitted.size() == 1,
         "snapshot restore safely falls back to one token");
  Expect(restored->DsparkStatistics().steps == 0,
         "snapshot restore does not draft across a support-cache gap");
}

void CheckDsparkSessionBatch(
    const std::shared_ptr<gufo::models::deepseek_v4_flash::Model>& model) {
  using gufo::models::deepseek_v4_flash::SessionDsparkBatchItem;

  constexpr std::size_t kComparedTokens = 24;
  constexpr std::array<std::string_view, 2> kPrompts{
      "Continue this technical explanation with concrete examples: virtual "
      "memory lets an operating system",
      "Explain why speculative decoding can improve language model inference "
      "while preserving the target model output.",
  };
  std::array<std::unique_ptr<gufo::models::deepseek_v4_flash::Session>, 2>
      sequential;
  std::array<std::unique_ptr<gufo::models::deepseek_v4_flash::Session>, 2>
      reference_batched;
  std::array<std::unique_ptr<gufo::models::deepseek_v4_flash::Session>, 2>
      batched;
  std::string error;
  for (std::size_t index = 0; index < kPrompts.size(); ++index) {
    const auto prompt = model->Tokenize(kPrompts[index]);
    Expect(!prompt.empty(), "DSpark batch prompt tokenization");
    sequential[index] = model->CreateSession(512, &error);
    reference_batched[index] = model->CreateSession(512, &error);
    batched[index] = model->CreateSession(512, &error);
    Expect(sequential[index] != nullptr, error.c_str());
    Expect(reference_batched[index] != nullptr, error.c_str());
    Expect(batched[index] != nullptr, error.c_str());
    Expect(sequential[index]->Sync(prompt, &error), error.c_str());
    Expect(reference_batched[index]->Sync(prompt, &error), error.c_str());
    Expect(batched[index]->Sync(prompt, &error), error.c_str());
  }

  double serial_seconds = 0.0;
  double batch_seconds = 0.0;
  std::array<std::vector<int>, 2> serial_tokens;
  for (std::size_t index = 0; index < sequential.size(); ++index) {
    while (serial_tokens[index].size() < kComparedTokens) {
      std::vector<int> emitted;
      const auto start = std::chrono::steady_clock::now();
      Expect(sequential[index]->DsparkStep(&emitted, &error), error.c_str());
      serial_seconds += std::chrono::duration<double>(
                            std::chrono::steady_clock::now() - start)
                            .count();
      serial_tokens[index].insert(serial_tokens[index].end(), emitted.begin(),
                                  emitted.end());
    }
  }

  auto run_batch =
      [&](auto& sessions, const char* support_body_setting,
          double* seconds) {
        Expect(setenv("GUFO_DEEPSEEK_DSPARK_SUPPORT_BODY_BATCH",
                      support_body_setting, 1) == 0,
               "set DSpark support body route");
        std::array<std::vector<int>, 2> tokens;
        while (tokens[0].size() < kComparedTokens ||
               tokens[1].size() < kComparedTokens) {
          std::array<std::vector<int>, 2> emitted;
          const std::array<SessionDsparkBatchItem, 2> items{{
              {
                  .session = sessions[0].get(),
                  .max_tokens = 32,
                  .emitted = &emitted[0],
              },
              {
                  .session = sessions[1].get(),
                  .max_tokens = 32,
                  .emitted = &emitted[1],
              },
          }};
          const auto start = std::chrono::steady_clock::now();
          Expect(model->DsparkStepBatch(items, &error), error.c_str());
          *seconds +=
              std::chrono::duration<double>(
                  std::chrono::steady_clock::now() - start)
                  .count();
          for (std::size_t index = 0; index < tokens.size(); ++index) {
            tokens[index].insert(tokens[index].end(), emitted[index].begin(),
                                 emitted[index].end());
          }
        }
        return tokens;
      };

  double reference_batch_seconds = 0.0;
  const auto reference_batch_tokens =
      run_batch(reference_batched, "0", &reference_batch_seconds);
  const auto batch_tokens = run_batch(batched, "1", &batch_seconds);

  std::uint64_t serial_emitted = 0;
  std::uint64_t batch_emitted = 0;
  std::uint64_t serial_support_drafted = 0;
  std::uint64_t serial_support_accepted = 0;
  std::uint64_t reference_support_drafted = 0;
  std::uint64_t reference_support_accepted = 0;
  std::uint64_t batch_support_drafted = 0;
  std::uint64_t batch_support_accepted = 0;
  for (std::size_t index = 0; index < batch_tokens.size(); ++index) {
    const auto serial_mismatch =
        std::mismatch(serial_tokens[index].begin(),
                      serial_tokens[index].begin() + kComparedTokens,
                      batch_tokens[index].begin());
    if (serial_mismatch.first !=
        serial_tokens[index].begin() + kComparedTokens) {
      const std::size_t token_index = static_cast<std::size_t>(
          serial_mismatch.first - serial_tokens[index].begin());
      std::cerr << "DSpark C1/W2 near-tie session=" << index
                << " token=" << token_index
                << " serial=" << *serial_mismatch.first
                << " batch=" << *serial_mismatch.second << '\n';
    }
    const auto reference_mismatch =
        std::mismatch(reference_batch_tokens[index].begin(),
                      reference_batch_tokens[index].begin() + kComparedTokens,
                      batch_tokens[index].begin());
    if (reference_mismatch.first !=
        reference_batch_tokens[index].begin() + kComparedTokens) {
      const std::size_t token_index = static_cast<std::size_t>(
          reference_mismatch.first - reference_batch_tokens[index].begin());
      std::cerr << "DSpark support body batch mismatch session=" << index
                << " token=" << token_index << " reference="
                << *reference_mismatch.first
                << " batch=" << *reference_mismatch.second
                << "\nreference:";
      for (const int token : reference_batch_tokens[index]) {
        std::cerr << ' ' << token;
      }
      std::cerr << "\nbatch:";
      for (const int token : batch_tokens[index]) {
        std::cerr << ' ' << token;
      }
      std::cerr << "\nserial:";
      for (const int token : serial_tokens[index]) {
        std::cerr << ' ' << token;
      }
      std::cerr << '\n';
    }
    const auto serial_stats = sequential[index]->DsparkStatistics();
    const auto reference_stats =
        reference_batched[index]->DsparkStatistics();
    const auto batch_stats = batched[index]->DsparkStatistics();
    serial_emitted += serial_tokens[index].size();
    batch_emitted += batch_tokens[index].size();
    serial_support_drafted += serial_stats.support_drafted;
    serial_support_accepted += serial_stats.support_accepted;
    reference_support_drafted += reference_stats.support_drafted;
    reference_support_accepted += reference_stats.support_accepted;
    batch_support_drafted += batch_stats.support_drafted;
    batch_support_accepted += batch_stats.support_accepted;
  }
  const double serial_acceptance =
      static_cast<double>(serial_support_accepted) / serial_support_drafted;
  const double reference_acceptance =
      static_cast<double>(reference_support_accepted) /
      reference_support_drafted;
  const double batch_acceptance =
      static_cast<double>(batch_support_accepted) / batch_support_drafted;
  Expect(batch_acceptance + 1.0e-12 >= reference_acceptance,
         "support body batching regressed DSpark acceptance");
  std::cout << "DeepSeek DSpark C2 batch: serial=" << serial_seconds * 1000.0
            << " ms reference_batch=" << reference_batch_seconds * 1000.0
            << " ms batch=" << batch_seconds * 1000.0
            << " ms speedup=" << serial_seconds / batch_seconds << "x combined="
            << static_cast<double>(batch_emitted) / batch_seconds
            << " support_body_speedup="
            << reference_batch_seconds / batch_seconds << "x"
            << " tok/s serial_acceptance=" << serial_acceptance
            << " reference_acceptance=" << reference_acceptance
            << " batch_acceptance=" << batch_acceptance
            << " serial_tokens=" << serial_emitted
            << " batch_tokens=" << batch_emitted << '\n';
}

}  // namespace

int main() {
  const char* model_path = std::getenv("GUFO_DEEPSEEK_V4_FLASH_MODEL");
  if (model_path == nullptr || model_path[0] == '\0') {
    std::cout << "SKIP: GUFO_DEEPSEEK_V4_FLASH_MODEL is not set\n";
    return 77;
  }

  using gufo::models::deepseek_v4_flash::Model;
  using gufo::models::deepseek_v4_flash::ModelOptions;

  const char* dspark_model_path =
      std::getenv("GUFO_DEEPSEEK_V4_FLASH_DSPARK_MODEL");
  std::string error;
  const auto model =
      Model::Load(model_path,
                  ModelOptions{
                      .max_context = 4096,
                      .prefill_chunk = 2048,
                      .power_percent = 100,
                      .dspark_model_path =
                          dspark_model_path != nullptr ? dspark_model_path : "",
                  },
                  &error);
  Expect(model != nullptr, error.c_str());
  Expect(model->VocabSize() > 0, "vocabulary size");
  Expect(!model->ModelName().empty(), "model name");

  if (std::getenv("GUFO_DEEPSEEK_V4_FLASH_CONVERSATIONAL_PREFILL_ONLY") !=
      nullptr) {
    Expect(!model->HasDspark(),
           "conversational prefill diagnostic requires target only");
    CheckConversationalPrefill(model);
    return 0;
  }

  if (std::getenv("GUFO_DEEPSEEK_V4_FLASH_SESSION_BATCH_ONLY") != nullptr) {
    Expect(!model->HasDspark(),
           "session batch diagnostic requires target only");
    CheckSessionBatch(model);
    return 0;
  }

  if (std::getenv("GUFO_DEEPSEEK_V4_FLASH_DSPARK_BATCH_ONLY") != nullptr) {
    Expect(model->HasDspark(),
           "DSpark batch diagnostic requires a support model");
    CheckDsparkSessionBatch(model);
    return 0;
  }

  const auto prompt =
      model->EncodeChat("You are a concise assistant.", "Reply with one word.");
  Expect(!prompt.empty(), "chat prompt tokenization");

  auto session = model->CreateSession(4096, &error);
  Expect(session != nullptr, error.c_str());
  Expect(session->Sync(prompt, &error), error.c_str());
  Expect(session->Position() == static_cast<int>(prompt.size()),
         "prefill position");

  const auto logits = session->CopyLogits(&error);
  Expect(!logits.empty(), error.c_str());
  Expect(std::all_of(logits.begin(), logits.end(),
                     [](float value) { return std::isfinite(value); }),
         "finite logits");

  const int checkpoint_position = session->Position();
  const int first_token = session->SelectNext(0.0F, nullptr);
  Expect(first_token >= 0, "first greedy token");
  Expect(!model->DecodeToken(first_token).empty(), "first token text");
  auto snapshot = session->SaveSnapshot(&error);
  Expect(snapshot != nullptr, error.c_str());
  Expect(snapshot->SizeBytes() > 0, "snapshot payload");
  Expect(session->Evaluate(first_token, &error), error.c_str());

  const int second_token = session->SelectNext(0.0F, nullptr);
  Expect(second_token >= 0, "second greedy token");
  Expect(session->Evaluate(second_token, &error), error.c_str());
  Expect(session->Position() == static_cast<int>(prompt.size()) + 2,
         "decode position");

  Expect(session->RestoreSnapshot(*snapshot, &error), error.c_str());
  Expect(session->Position() == checkpoint_position, "restored position");
  Expect(session->SelectNext(0.0F, nullptr) == first_token,
         "restored greedy token");
  Expect(session->CopyLogits(&error) == logits, "restored logits");

  CheckPinnedTrajectory(model);
  CheckBatchedPrefill(model);
  CheckConversationalPrefill(model);
  if (!model->HasDspark()) {
    CheckSessionBatch(model);
  }
  if (dspark_model_path != nullptr && dspark_model_path[0] != '\0') {
    CheckDsparkPromptSeed(model);
  }

  std::cout << "DeepSeek V4 Flash model/session test passed\n";
  return 0;
}
