add_library(gufo_cache STATIC completion.cpp identity.cpp ledger.cpp)
target_include_directories(gufo_cache PUBLIC ${PROJECT_SOURCE_DIR})
target_link_libraries(gufo_cache PUBLIC Threads::Threads)
if (BUILD_TESTING)
  target_compile_options(gufo_cache PRIVATE -UNDEBUG)
endif()
if (GUFO_BUILD_TOOLS)
  add_executable(cache_ledger_bench ${PROJECT_SOURCE_DIR}/tests/cache/ledger_bench.cpp)
  target_link_libraries(cache_ledger_bench PRIVATE gufo_cache)
endif()
